export const PROJECTS = [
  {
    id: "helder-system",
    title: "Helder System Clinic",
    category: "SaaS / Saúde",
    status: "Em Produção",
    year: "2025 — 2026",
    shortDescription:
      "Plataforma SaaS Multi-Tenant completa de gestão para clínicas de medicina integrativa, emagrecimento e estética.",
    fullDescription:
      "Sistema robusto que unifica toda a operação clínica em uma única plataforma: desde o agendamento e prontuário eletrônico até a gestão financeira e controle de estoque. Com billing integrado e inteligência artificial avançada para análise de laudos e suporte à decisão clínica.",
    role: "Founder & Desenvolvedor Full Stack",
    impact: [
      "20 módulos completos em produção",
      "210+ componentes de interface",
      "42+ serviços de backend",
      "45+ tabelas de banco de dados",
      "Arquitetura Multi-Tenant com isolamento total de dados",
    ],
    features: [
      "Dashboard inteligente multi-clínica",
      "Prontuário eletrônico e prescrições médicas",
      "Sistema de agendamentos com notificações",
      "Módulos de tratamentos especializados",
      "IA avançada para análise de laudos médicos",
      "Billing SaaS com gestão de assinaturas",
      "Painel SuperAdmin com métricas de MRR e Churn",
      "Gestão de equipamentos, estoque e financeiro",
    ],
    tech: [
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "Prisma",
      "PostgreSQL",
      "Supabase",
      "Stripe",
      "Google Gemini AI",
      "Tailwind CSS",
      "Radix UI",
    ],
    metrics: {
      modules: "20",
      components: "210+",
      services: "42+",
      tables: "45+",
    },
    color: "#D4A853",
  },
  {
    id: "helder-assistente",
    title: "Helder Assistente IA",
    category: "Inteligência Artificial",
    status: "Em Produção",
    year: "2025 — 2026",
    shortDescription:
      "Sistema multi-agente de IA que atua como um C-Suite virtual, automatizando decisões estratégicas e operacionais do negócio.",
    fullDescription:
      "Ecossistema de inteligência artificial com 8 agentes especializados (CEO, CTO, CMO, CFO, COO, CSO e mais) que operam de forma autônoma para captação de leads, análise de dados, gestão de tarefas e tomada de decisão assistida. Integrado via Telegram e Command Center web.",
    role: "Criador & Arquiteto de IA",
    impact: [
      "8 agentes de IA especializados operando em produção",
      "Sistema de captação de leads automatizado",
      "Command Center com dashboard de analytics em tempo real",
      "Integração via bot do Telegram para acesso mobile",
      "Base de conhecimento RAG para decisões contextualizadas",
    ],
    features: [
      "8 agentes C-Suite especializados (CEO, CTO, CMO, CFO...)",
      "Command Center web com dashboard completo",
      "Sistema de tarefas com rastreabilidade",
      "CRM integrado para gestão de leads",
      "Analytics e relatórios de performance",
      "Bot do Telegram para acesso mobile",
      "Base de conhecimento com RAG",
      "Monitoramento de custos e tokens de IA",
    ],
    tech: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "Docker",
      "Ollama",
      "LLM Local",
      "Telegram API",
      "Tailwind CSS",
      "shadcn/ui",
    ],
    metrics: {
      agents: "8",
      modules: "6+",
      integrations: "4+",
    },
    color: "#4CAF50",
  },
  {
    id: "helder-app",
    title: "Helder App",
    category: "Mobile / IA",
    status: "Em Desenvolvimento",
    year: "2025 — 2026",
    shortDescription:
      "Aplicação mobile com inteligência artificial Gemini para suporte e interação inteligente no ecossistema Helder System.",
    fullDescription:
      "App que integra o poder da IA Google Gemini para oferecer assistência inteligente aos usuários do ecossistema Helder System. Interface conversacional moderna com processamento de linguagem natural para consultas, agendamentos e suporte.",
    role: "Desenvolvedor Full Stack",
    impact: [
      "Interface conversacional com IA Gemini",
      "Integração direta com o ecossistema Helder System",
      "Experiência mobile-first otimizada",
    ],
    features: [
      "Chat inteligente com Google Gemini",
      "Processamento de linguagem natural",
      "Interface mobile responsiva",
      "Integração com ecossistema Helder",
    ],
    tech: [
      "Node.js",
      "Google Gemini API",
      "AI Studio",
    ],
    metrics: {
      aiModel: "Gemini",
      platform: "Mobile",
    },
    color: "#2196F3",
  },
  {
    id: "apr-pro",
    title: "APR Pro",
    category: "SaaS / Segurança do Trabalho",
    status: "MVP em Desenvolvimento",
    year: "2025 — 2026",
    shortDescription:
      "SaaS multi-tenant para geração automatizada de Análise Preliminar de Risco (APR) com Inteligência Artificial.",
    fullDescription:
      "Plataforma que reduz drasticamente o tempo de criação de APRs complexas utilizando IA avançada. Garante o mapeamento de riscos e medidas preventivas padronizadas, com recursos de isolamento e gestão de múltiplos clientes e equipes de forma segura.",
    role: "Criador & Desenvolvedor Full Stack",
    impact: [
      "Redução drástica no tempo de criação de APRs",
      "Geração automatizada com IA (GPT-4o)",
      "Gestão multi-tenant para empresas B2B",
      "3 planos de assinatura (Free, Pro, Enterprise)",
    ],
    features: [
      "Motor de geração de APR com IA em tempo real (streaming)",
      "Gestão de ciclo de vida do documento (Draft → Review → Approved)",
      "Templates customizados para reuso",
      "Sistema RBAC com 4 níveis de acesso",
      "Exportação em PDF de alta qualidade",
      "Billing integrado com planos SaaS",
    ],
    tech: [
      "React",
      "TypeScript",
      "Vite",
      "Supabase",
      "OpenAI GPT-4o",
      "Tailwind CSS",
      "Zod",
      "React Query",
    ],
    metrics: {
      roles: "4 (RBAC)",
      plans: "3 tiers",
      aiModel: "GPT-4o",
    },
    color: "#FF9800",
  },
  {
    id: "curriculo-pro",
    title: "Currículo Pro IA",
    category: "SaaS / Produtividade",
    status: "MVP em Desenvolvimento",
    year: "2025 — 2026",
    shortDescription:
      "Aplicação que transforma a Carteira de Trabalho Digital (CTPS) ou currículo antigo em um documento profissional moderno usando IA.",
    fullDescription:
      "Em menos de 3 minutos, qualquer pessoa transforma sua CTPS ou currículo desatualizado em um currículo profissional moderno, otimizado para processos seletivos. A IA extrai dados automaticamente de PDFs/imagens, refina textos com linguagem profissional e gera um score de qualidade.",
    role: "Criador & Desenvolvedor Full Stack",
    impact: [
      "Processamento de CTPS em menos de 3 minutos",
      "Extração automática de dados via IA",
      "Múltiplos templates profissionais",
      "Score de qualidade do currículo",
    ],
    features: [
      "Upload de PDF/PNG/JPG com extração automática via IA",
      "Editor com preview em tempo real",
      "Múltiplos templates de design profissional",
      "IA que refina resumo e descrições de experiência",
      "Score de qualidade do currículo",
      "Exportação em PDF de alta qualidade",
    ],
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Google Gemini AI",
      "OCR",
    ],
    metrics: {
      timeToResult: "< 3 min",
      aiModel: "Gemini",
    },
    color: "#E91E63",
  },
  {
    id: "pousada-portugueza",
    title: "Estratégia Digital — Pousada",
    category: "Marketing Digital / SaaS",
    status: "Projeto Entregue",
    year: "2024 — 2025",
    shortDescription:
      "Planejamento estratégico digital completo e desenvolvimento de sistema de gestão próprio para pousada no litoral do RJ.",
    fullDescription:
      "Projeto completo que abrangeu desde a análise SWOT e planejamento de marketing digital até o desenvolvimento de um sistema próprio de gestão de reservas estilo Airbnb. Incluiu estratégias de Google Ads, SEO, redes sociais e um sistema com motor de reservas online, CRM de hóspedes e calendário de disponibilidade.",
    role: "Consultor Digital & Desenvolvedor",
    impact: [
      "Análise SWOT completa do negócio",
      "Estratégia de Google Ads e Meta Ads",
      "Sistema próprio de gestão de reservas",
      "Landing page otimizada para conversão",
      "SEO e Google Meu Negócio otimizados",
    ],
    features: [
      "Planejamento estratégico digital (SWOT, KPIs, metas)",
      "Campanhas de Google Ads com segmentação geográfica",
      "Otimização SEO e Google Meu Negócio",
      "Motor de reservas online em tempo real",
      "CRM para gestão de hóspedes e inquilinos",
      "Landing page com design otimizado para conversão",
      "Integração com OTAs (Booking, Airbnb)",
    ],
    tech: [
      "Google Ads",
      "Meta Ads",
      "SEO",
      "WordPress",
      "Google Meu Negócio",
      "WhatsApp Business",
    ],
    metrics: {
      kpis: "12+",
      channels: "6+",
    },
    color: "#00BCD4",
  },
] as const;
